// import { doc, setDoc } from "firebase/firestore";
// For storing data in database with unique Id generated by firestore
// use addDoc
import { collection, addDoc } from "firebase/firestore";
import { db } from "../../../firebase.js";
export default {
  state() {
    return {};
  },
  actions: {
    async addDataToDatabase(_, payload) {
      try {
        // Add a new document with custom id.
        // await setDoc(doc(db, "data", "one"), payload);
        // Add a new document with a generated id.
        await addDoc(collection(db, "data"), payload);
      } catch (error) {
        console.log(error.message);
      }
    },
  },
  mutations: {},
  getters: {},
};
